name: Deploy sls

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: rlespinasse/github-slug-action@v5
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: 24
    - run: npm ci
    - run: |
        npx sls deploy --stage $GITHUB_REF_SLUG_URL
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
