name: Deploy sls

on:
  push:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: 24
    - run: npm ci
    - name: Install poetry
      uses: abatilo/actions-poetry@v4
    - name: Create slug
      id: slug
      run: |
        # Create a slug from the branch name
        # Store it for next steps.
        echo "slug=$(echo "$GITHUB_REF_NAME" | iconv -t ascii//TRANSLIT | sed -r s/[~\^]+//g | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)" >> $GITHUB_OUTPUT
    - run: |
        poetry install
        eval $(poetry env activate)
        npx sls deploy --stage $GITHUB_REF_SLUG_URL
      env:
        # From the slug step.
        GITHUB_REF_SLUG_URL: ${{ steps.slug.outputs.slug }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
        DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
        DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
        DROPBOX_PATH: ${{ secrets.DROPBOX_PATH }}
